## Synthetic population pipeline for Hannover
## based on the synpp package

# This is the path to a directory where the pipeline can store temporary data
working_directory: /set/your/path/to/cache

# This section defines which parts of the pipeline should be run
run:
  - synthesis.output
  - matsim.output

# Here the configuraiton of the pipeline starts
config:
  # Some general configuration
  processes: 8

  # Define whether to use ENTD or EGT as the household travel survey (HTS)
  hts: entd

  # Define sampling rate and random seed for the output population
  sampling_rate: 0.01
  random_seed: 1234
 
  # Paths to the input data and where the output should be stored
  data_path: /set/your/path/to/data
  output_path: /set/your/path/to/output
  output_prefix: hannover_1pct_

  # Only interesting if you run the simulation
  java_memory: 12G

  # Defaults for Hannover
  home_location_sampling: weighted
  mode_choice: false
  matching_attributes: ["sex", "age_class", "has_license"]

  gtfs_path: gtfs
  osm_path: osm


# Overrides for the hannover pipeline compared to the Île-de-France pipeline
aliases:
  data.census.filtered: hannover.ipf.attributed

