## Synthetic population pipeline for asuncion
## based on the synpp package

# This is the path to a directory where the pipeline can store temporary data
working_directory: cache

# This section defines which parts of the pipeline should be run
run:
  - asuncion.primary_locations_assignment
#  - analysis.asuncion.ivt_style.compare_ipu
config:
  # Some general configuration
  processes: 8

  # Define whether to use ENTD or EGT as the household travel survey (HTS)
  hts: entd

  # Define sampling rate and random seed for the output population
  sampling_rate: 0.01
  acquisition_sample_size: 1
  random_seed: 1234

  # Paths to the input data and where the output should be stored
  data_path: ../raw_data/Asuncion
  output_path: output
  output_prefix: asuncion_1pct_
  asuncon.population_shp: shapefiles/census_district_shapefiles/SECC_CE_20220101.shp
  asuncion.buildings_path: catastre_buildings/all_buildings.gpkg
  osm_path_asuncion: osm/paraguay-260810.osm.pbf
  check_spatial_codes: True
  analysis_path: output/analysis
  osmconvert_binary: "/cluster/scratch/snekula/sutlab/sutLab/osmconvert"
  #osmconvert_binary: "/home/xnekul/windir/ETH_SUTlab/sutLab/osmconvert"

  simulation_output_dir: output/simulation
  # Only interesting if you run the simulation
  java_memory: 6G

  # Defaults for asuncion
  

  pipeline_crs: "EPSG:32721"
  home_location_sampling: weighted
  mode_choice: True
  matching_attributes: ["sex", "age_class", "has_license"]
  IPU_aggregation_level: "commune_id"
  commune_equivalent: "district" # or borrough

  education_graduation_age: 
    school: 17
     # university all above last entry
  education_assignment_method: "distance"
  work_assignment_method: "gravity"


  osm_path: osm
  osmosis_binary: osmosis/bin
  gtfs_path: gtfs/Line1

  eqasim_commit: f375a37
  eqasim_version: "2.0.0"
  eqasim_branch: "sutlab" 


aliases:
  data.hts.entd.raw: asuncion.data.hts.entd.raw
  data.hts.entd.filtered: asuncion.data.hts.entd.filtered
  data.hts.entd.cleaned: asuncion.data.hts.entd.cleaned
  data.hts.entd.reweighted: asuncion.data.hts.entd.reweighted

  synthesis.population.sampled: asuncion.ipu.attributed
  data.census.filtered: asuncion.ipu.attributed
  data.spatial.iris: asuncion.data.spatial.iris
  data.spatial.codes: asuncion.entd_codes

  synthesis.population.enriched: asuncion.synthesis.population.enriched

  synthesis.population.income.selected: asuncion.income
  synthesis.population.spatial.home.zones: asuncion.homes

  synthesis.locations.home.locations: asuncion.locations.home
  synthesis.locations.secondary: asuncion.locations.secondary
  synthesis.locations.work: asuncion.locations.work
  synthesis.locations.education: asuncion.data.education
  
  
  data.od.weighted: asuncion.gravity.model_new
  synthesis.population.spatial.primary.locations: asuncion.primary_locations_assignment 
  synthesis.population.spatial.primary.candidates: asuncion.gravity.work_candidates


  synthesis.population.trips: asuncion.synthesis.population.trips
  synthesis.population.spatial.locations: asuncion.synthesis.population.spatial.locations
  synthesis.population.spatial.secondary.locations: asuncion.synthesis.population.spatial.secondary.locations

  matsim.simulation.prepare: asuncion.matsim.simulation.prepare
  matsim.simulation.run: asuncion.matsim.simulation.run
  matsim.scenario.prepare: matsim.simulation.prepare # matsim.scenario.prepare stage is not used in simulation at all
  matsim.scenario.population: asuncion.matsim.scenario.population


  
