## Synthetic population pipeline for Hannover
## based on the synpp package

# This is the path to a directory where the pipeline can store temporary data
working_directory: /set/your/path/to/cache

# This section defines which parts of the pipeline should be run
run:
  - synthesis.output
  #- matsim.output
  - analysis.hannover.ivt_style.analysis

# Here the configuraiton of the pipeline starts
config:
  # Some general configuration
  processes: 8

  # Define whether to use ENTD or EGT as the household travel survey (HTS)
  hts: entd

  # Define sampling rate and random seed for the output population
  sampling_rate: 0.01
  random_seed: 1234
 
  # Paths to the input data and where the output should be stored
  data_path: /set/your/path/to/data
  output_path: /set/your/path/to/output
  output_prefix: hannover_1pct_

  # Only interesting if you run the simulation
  java_memory: 12G

  # Defaults for Hannover
  home_location_sampling: weighted
  mode_choice: false
  matching_attributes: ["sex", "age_class", "has_license"]

  gtfs_path: gtfs
  osm_path: osm


# Overrides for the hannover pipeline compared to the Île-de-France pipeline
aliases:
  data.census.filtered: hannover.ipf.attributed
  synthesis.population.income.selected: hannover.income
  synthesis.population.spatial.home.zones: hannover.homes
  synthesis.locations.home.locations: hannover.locations.home
  synthesis.locations.education: hannover.locations.education
  synthesis.locations.secondary: hannover.locations.secondary
  synthesis.locations.work: hannover.locations.work
  data.od.weighted: hannover.gravity.model
  data.spatial.iris: hannover.data.spatial.iris
  data.spatial.codes: hannover.entd_codes
  synthesis.population.spatial.primary.locations: hannover.locations.synthesis.replacement
  synthesis.population.enriched: hannover.synthesis.population.enriched
  matsim.simulation.prepare: hannover.matsim.simulation.prepare
  data.hts.entd.raw: hannover.data.hts.entd.raw
  data.hts.entd.filtered: hannover.data.hts.entd.filtered
  data.hts.entd.cleaned: hannover.data.hts.entd.cleaned

