## Synthetic population pipeline for seville
## based on the synpp package

# This is the path to a directory where the pipeline can store temporary data
working_directory: cache

# This section defines which parts of the pipeline should be run
run:
#  - seville.gravity.primary_locations
  - analysis.seville.ivt_style.analysis

config:
  # Some general configuration
  processes: 8

  # Define whether to use ENTD or EGT as the household travel survey (HTS)
  hts: entd

  # Define sampling rate and random seed for the output population
  sampling_rate: 0.01
  acquisition_sample_size: 1
  random_seed: 1234

  # Paths to the input data and where the output should be stored
  data_path: ../raw_data/Seville
  output_path: output
  output_prefix: seville_1pct_
  seville.population_shp: shapefiles/census_district_shapefiles/SECC_CE_20220101.shp
  seville.buildings_path: catastre_buildings/all_buildings.gpkg
  osm_path_seville: osm/andalucia-latest.osm.pbf
  check_spatial_codes: True
  analysis_path: output/analysis
  osmconvert_binary: "/cluster/scratch/snekula/sutlab/sutLab/osmconvert"
  #osmconvert_binary: "/home/xnekul/windir/ETH_SUTlab/sutLab/osmconvert"

  simulation_output_dir: output/simulation
  # Only interesting if you run the simulation
  java_memory: 6G

  # Defaults for seville
  

  home_location_sampling: weighted
  mode_choice: True
  matching_attributes: ["sex", "age_class", "has_license"]

  gtfs_path: gtfs/Line1
  
  osm_path: osm
  osmosis_binary: osmosis/bin

  seville_locations_area_selection: 'agglomeration'
  seville_census_area_selection: 'agglomeration' 

  IPU_aggregation_level: "departement_id"
  weighted_trips: True

  missing_trips_for_young_people: False
  eqasim_commit: f375a37
  eqasim_version: "2.0.0"
  eqasim_branch: "sutlab" 


aliases:



  synthesis.population.sampled: seville.ipu.attributed
  data.census.filtered: seville.ipu.attributed
  synthesis.population.income.selected: seville.income
  synthesis.population.spatial.home.zones: seville.homes
  synthesis.locations.home.locations: seville.locations.home
  synthesis.locations.secondary: seville.locations.secondary
  synthesis.locations.work: seville.locations.work
  data.od.weighted: seville.gravity.model_new

  data.spatial.iris: seville.data.spatial.iris
  data.spatial.codes: seville.entd_codes

  synthesis.population.spatial.primary.locations: seville.locations.synthesis.replacement
  synthesis.population.enriched: seville.synthesis.population.enriched
 
  data.hts.entd.raw: seville.data.hts.entd.raw
  data.hts.entd.filtered: seville.data.hts.entd.filtered
  data.hts.entd.cleaned: seville.data.hts.entd.cleaned
  data.hts.entd.reweighted: seville.data.hts.entd.reweighted


  matsim.simulation.prepare: seville.matsim.simulation.prepare
  matsim.simulation.run: seville.matsim.simulation.run
  matsim.scenario.prepare: matsim.simulation.prepare # matsim.scenario.prepare stage is not used in simulation at all
  matsim.scenario.population: seville.matsim.scenario.population
  data.gtfs.cleaned: seville.data.gtfs.cleaned
  synthesis.output: seville.output

  synthesis.population.trips: seville.synthesis.population.trips

  synthesis.population.spatial.locations: seville.synthesis.population.spatial.locations

  synthesis.population.spatial.secondary.locations: seville.synthesis.population.spatial.secondary.locations


  
  synthesis.population.spatial.primary.locations: seville.gravity.primary_locations

  
  
  synthesis.population.spatial.primary.candidates: seville.gravity.work_candidates
  synthesis.locations.education: seville.data.education.merged  

